essexcountycouncil/essex-intranet-drupal

- themes/custom/essex/css/overrides.css
- themes/custom/essex/css/variables.css
And black border.
Components affected:
- Sidebar components (related topics etc.)
- Newsroom sidebars
- Guide contents component
> ECCI-212: Changes all grey link boxes to have white background 

- .gitignore
- assets/composer/settings.local.php
- config/default/openid_connect.client.essex.yml
- config/default/openid_connect.client.nomensa.yml
This supplies:
- addition to `settings.local.php` to read an environment variable named `OPENID_CONNECT_PARAMS` and process it to assign the right values to access Azure B2C
- config files for the `openid_connect_client`s again with non-functioning data
The `OPENID_CONNECT_PARAMS` env var is a json string in this format:
```
{"always_save_userinfo":false,"connect_existing_users":true,"override_registration_settings":true,"end_session_enabled":true,"user_login_display":"above","redirect_login":"user","clients":{"nomensa":{"status":true,"settings":{"client_id":"clientid","client_secret":"secret_from_generated_key","tenant":"tenant_name"}},"essex":{"status":true,"settings":{"client_id":"clientid","client_secret":"secret_from_generated_key","tenant":"tenant_name"}}}}
```
To work with DDEV, …
> ECCI-133: SSO supplied via env vars.

- patches/entitygroupfield-groupv3-2.patch
The groupv3-2 patch includes aspects of the other two patches. This removes the hunks at https://www.drupal.org/files/issues/2022-10-14/issue-3315323-3.patch (three single line changes) plus the single line change for the get at line 71 of src/Plugin/Field/FieldWidget/EntityGroupFieldWidgetBase.php from [the install.patch](https://github.com/essexcountycouncil/essex-intranet-drupal/blob/develop/patches/entitygroupfield-install.patch#L36-L48)
> Fix patch duplication

- composer.json
> ECCI-217: Fixes broken groups admin dropdown.

- composer.lock
Just adds the [newer version of the content ownership module](https://github.com/essexcountycouncil/content_ownership/pull/8).
> ECCI-328: Adding the newer version of content_ownership.

- themes/custom/essex/css/overrides.css
- Decreases spacing above 'Latest news'
- Increases spacing between newsroom teaser component items
- Removes margin-right on date
> ECCI-342: Newsroom teaser style updates

- themes/custom/essex/css/overrides.css
- Adds a max-height of 200px to default media with text component on mobile, 250px on small tablet
- Reduces padding between Quick Actions and the content below it
> ECCI-342 & 323: Adds a max-height to default media with text component and reduces padding below quick actions

- config/default/core.menu.static_menu_link_overrides.yml
> ECCI-359: Move footer menu admin link to bottom of Content menu.

- config/default/block.block.essex_localgov_breadcrumbs_scarfolk.yml
By deselecting all of the content types in the breadcrumb's block config page (making it so that the breadcrumbs will display on every page) they then appear on the `/csearch` cludo page.
There was only one content type which didn't have the tickbox displaying prior to this: the `subsite_overview` content type. Even after making this change the breadcrumbs do not display on `subsite_overview` pages anyway.
So having tried to code my way out of this, in the end, the **no code** approach was the right solution.
> ECCI-361: Breadcrumbs don't display on subsite_overview pages anyway.

- composer.json
- composer.lock
- config/default/contact.form.personal.yml
- config/default/contact.settings.yml
- config/default/core.extension.yml
- config/default/smtp.settings.yml
- config/default/system.mail.yml
This enables the contact module for ECC testing. It also adds the SMTP auth module, to route outbound emails via SMTP. The dev site has a mailcatcher instance running on the email hostname.
> Add email support and contact module

- composer.json
- composer.lock
- config/default/config_ignore.settings.yml
- config/default/core.extension.yml
- config/default/facets.facet.localgov_events_locality.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_directories_page.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_directories_venue.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_directory.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_directory_promo_page.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_event.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_guides_overview.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_guides_page.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_news_article.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_newsroom.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_services_landing.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_services_page.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_services_status.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_services_sublanding.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_step_by_step_overview.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_step_by_step_page.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_subsites_overview.yml
- config/default/simple_sitemap.bundle_settings.default.node.localgov_subsites_page.yml
- config/default/simple_sitemap.custom_links.default.yml
- config/default/simple_sitemap.settings.yml
- config/default/simple_sitemap.sitemap.default.yml
- config/default/simple_sitemap.sitemap.index.yml
- config/default/simple_sitemap.type.default_hreflang.yml
- config/default/simple_sitemap.type.index.yml
ECCI-449 - Sitemap module was removed from Intranet (ECCI-388) but is required for Cludo search
- Enable the module
- Set all content types to be indexed
- Set base url to https://beta.intranet.essex.gov.uk/
- Add simple_sitemap.settings to Config Ignore so base URL can be changed per environment
ECCI-386 - add oidc_auto_login.settings to Config Ignore so that it can be disabled on some environments
> ECCI-449: Reinstall Simple XML Sitemap module.

- themes/custom/essex/css/preliminary.css
...and also between media and text components on tablet.
- Tested and can confirm these styles will affect the media and text components only
- Styles will only work if configuration of page is as shown in the ticket
- Order:
- text component
- ...rest of components
- the styles targets the first field in the page and then goes into that field and alters the margin of the component section
- Also had to alter the padding on the `.layout--twocol > .layout__region--second`
> ECCI-471: reduce space between hero and content

- composer.json
- composer.lock
Move the B2C login from a dev release to the Drupal release. Pin to beta, to allow Drupal 10 support.
> Switch B2C to an official release

- modules/custom/localgov_restricted_content/localgov_restricted_content.module
- Adds a constant to enable/disable the feature altogether
- If enabled, a check of the content type is made to determine whether the form element should be disabled
- This allows the existing work in progress to remain and not hinder progress with interim releases.
- **Caveat no. 1**: If content of anything type other than `news_article` or `newsroom` have been marked as `Restricted content` they won't be able to be unmarked until the feature is switched off.
- **Caveat no. 2**: There is no GUI interface to enable/disable this - it requires a tweak to code and a deployment
- **Caveat no. 3**: Editors will see the `Restricted content` form element on all content types still, but will be unable to change it when this is enabled.
> ECCI-488: Feature switch for the Restricted content form element

- Dockerfile-nginx
- nginx-conf/nginx.conf
This realigns the intranet nginx config with the one from the public site, which removes the conditional noindex implementation and replaces it with the environment variable-based one.
By aligning these, it also:
* Adds limited beta mode (albeit disabled) and sets the intranet healthcheck url
* Retains the fastcgi changes in PR #257 (ECCI-487)
* Adds canonical url environment variable support, which will be needed for go-live
* Allows later versions of the official nginx image to be used in builds
> Update nginx config with fixed noindex support

- config/default/core.entity_form_display.node.localgov_newsroom.default.yml
- config/default/core.entity_view_display.node.localgov_newsroom.default.yml
- config/default/core.entity_view_display.node.localgov_newsroom.full_anonymous.yml
- config/default/field.field.node.localgov_newsroom.localgov_page_components.yml
- config/default/field.storage.node.localgov_page_components.yml
- themes/custom/essex/css/preliminary.css
This provides editors the option to add a single page component to the bottom of newsroom pages using the pattern used for doing so on service pages.
- The add/edit page:
- The default display:
> ECCI-464: Add a component to the bottom of newsroom pages.

- Dockerfile-drupal
Some pages are hitting a PHP memory limit, despite there being plenty of free memory available. This increases the fpm limit to 512mb.
> ECCI-494: Increase PHP memory limit

- Dockerfile-nginx
- nginx-conf/nginx.conf
Repeat PR due to forced update on branch.
This realigns the intranet nginx config with the one from the public site, which removes the conditional noindex implementation and replaces it with the environment variable-based one.
By aligning these, it also:
* Adds limited beta mode (albeit disabled) and sets the intranet healthcheck url
* Retains the fastcgi changes in PR #257 (ECCI-487)
* Adds canonical url environment variable support, which will be needed for go-live
* Allows later versions of the official nginx image to be used in builds
> ECCI-425: Update nginx config with fixed noindex support

- modules/custom/localgov_restricted_content/src/RestrictedContent.php
This amends the `isAncestorRestricted` method of `localgov_restricted_content` to detect cases where a node has been set as its direct parent, and breaks the parent-recursion chain by restricting the content. It won't detect cases where there's a cycle of length > 1, but this allows editing of a page on the intranet where this was already set.
> ECCI-494: Fix memory error caused by a node being its own parent

- config/default/core.entity_view_display.node.localgov_newsroom.default.yml
- config/default/core.entity_view_display.node.localgov_subsites_overview.default.yml
- themes/custom/essex/templates/content/node--localgov-newsroom--full.html.twig
- themes/custom/essex/templates/field/field--paragraphs-library-item--label--paragraphs-library-item.html.twig
- Also, the labels for the page_components don't appear if choose to be hidden - this needs to be examine in testing on other pages which have page_components to ensure no regressions have been introduced.
- Two content types have had the `content_modertation_control` field changed back to hidden
> ECCI-464: Page components are at the bottom of the newsroom now.

- config/default/editor.editor.wysiwyg.yml
- The right chevron will appear in the WYSIWYG selector
- Instructions based on the [Drupal docs](https://www.drupal.org/docs/contributed-modules/font-awesome-icons/using-font-awesome-icons-in-ckeditor)
Although you can choose any of the FA icons available when editing, you **must** add the `chevron-right` to get any icon whatsoever:
> ECCI-517: FA button added to CKEditor.

- themes/custom/essex/css/news.css
- themes/custom/essex/css/overrides.css
> ECCI-516: Spacing between News Article body text and Related News block too small

- composer.json
- composer.lock
This will only be used to export single bits of content added to pre-prod that content editors want copying to the prod environment.
It will be enabled manually on both environments just long enough to do the export and import of content, and then disabled.
> ECCI-514: Single Content Sync module added to support the release.

- config/default/field.field.media.image.field_media_image.yml
- No conversions to WebP are done, just allows them to be added and used
- Imagemagick and do the cropping as necessary
> ECCI-484: WebP files can now be uploaded.

- assets/composer/robots.txt
> ECCI-519: Robots.txt to allow Cludo.

- config/default/automated_cron.settings.yml
ECCI-439 stopped Cron running automatically. Set it to run every 900 seconds (15 minutes.)
> ECCI-521: Set Automatic Cron to run every 900 seconds

- composer.json
- composer.lock
Error when running `drush deploy` when deploying to Dev:
```
SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege and binary logging is enabled (you *might*   
want to use the less safe log_bin_trust_function_creators variable): DROP TRIGGER IF EXISTS paragraph__field_news_cards_der_update
```
See https://www.drupal.org/project/dynamic_entity_reference/issues/3382404
There is no patch yet but one recommendation is to downgrade the module.
> ECCI-442: Downgrade Dynamic Entity Reference module to fix SQL error.

- themes/custom/essex/css/overrides.css
> [bugfix/ECCI-417-h1-and-h2-spacing] h1 and h2 spacing fix

- composer.lock
In this case, we needed to do a `composer require essexcountycouncil/ecc_theme` to get the latest.
> Update composer.lock to get the right version of essex_theme.

- config/default/block.block.guidecontents.yml
- config/default/block.block.guidesprevnextblock.yml
- config/default/block.block.partofstepheading.yml
- config/default/block.block.subsitebanner.yml
- config/default/block.block.subsitenavigation.yml
- config/default/block.block.views_block__localgov_step_by_step_navigation_prev_next.yml
- config/default/block.block.views_block__localgov_step_by_step_navigation_steps.yml
- config/default/block.block.views_block__localgov_step_by_step_navigation_steps_for_overview.yml
- modules/custom/localgov_restricted_content/localgov_restricted_content.services.yml
- modules/custom/localgov_restricted_content/src/EventSubscriber/PageHeaderSubscriber.php
- modules/custom/localgov_restricted_content/src/Plugin/Condition/RestrictedContent.php
- modules/custom/localgov_restricted_content/src/RestrictedContent.php
- themes/custom/essex/templates/content/node--full-anonymous.html.twig
Anonymous users should only see the title, image and sign-in message on pages marked as restricted content. Already implemented for news.
- Create Restricted Content condition
- Add condition to blocks that should be hidden on restricted content pages for anonymous users
- Hide summary text in page header block on restricted content
- Cleanup node--full-anonymous template so it displays any available fields. In practice, the anonymous display mode only has the restricted content message
Same as already delivered for news articles and newsrooms
Many pages have blocks displayed so a new condition was required to hide them if the user isn't logged in and the page is …
> ECCI-423: Apply restricted content to all non-news content types

- .gitlab-ci.yml
- composer.lock
This is to upgrade composer and `geocoder-php/common-http` to deal with a security issue and an abandoned package, both of which cause composer audit to fail.
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-24821
- One thing which wasn't immediately apparent while trying to resolve originally was that a `composer update composer/composer` was also required
- The latest `wodby/php` docker image didn't have Composer ^2.7, so a `composer self-update` was added to the script section of the test job in the pipeline.
> ECCI-0: Upgrade composer to address CVE-2024-24821.

- config/default/block.block.ecc_theme_intranet_guidecontents.yml
Hide title of the block "Guide Contents"
> ECCI-442: Hide title for Guide Contents block.

- composer.lock
Bumps the shared theme version to 1.0.18.
This removes the `grid-template-columns` property which was causing the massive gap between columns. See the shared theme [release](https://github.com/essexcountycouncil/ecc_theme/releases/tag/1.0.18).
> ECCI-539: Excessive gap in featured teasers removed.

- config/default/user.role.analytics.yml
Drupal 10 throws an error when it finds that role has a permission that doesn't exist. This one must have occurred when the version of Google Tag was changed.
> Change GTM permission to prevent error.

- .gitlab-ci.yml
- New jobs to deploy to Prod without going to Preprod. This require the containers to be imported from Dev.
- Revert deploy-to-prod to depend on deploy-to-preprod
> Gitlab CI jobs to deploy straight to Prod.

- config/default/eu_cookie_compliance.cookie_category.analytics_cookies.yml
Hotjar has been added through GTM so the EU Cookie Control text has to be updated.
> LP-65: Add Hotjar to text for analytics cookies.

- config/default/field.field.media.document.field_media_document.yml
Allow `.zip` as file extensions for document upload
> LP-75: Add .zip to allowed file formats.

- config/default/block.block.ecc_theme_intranet_views_block__published_review_dates_block_publish_review_dates.yml
https://eccservicetransformation.atlassian.net/browse/LP-85
The change is: allow review dates views block to show on `localgov_step_by_step_page` nodes.
> Make sure review dates appear on step by step pages

- .gitlab-ci.yml
Replace apk with apt-get in gitlab-ci
Pipelines started failing recently as apk isn't in the new Docker image
https://techcommunity.microsoft.com/t5/azure-tools-blog/azure-cli-docker-container-base-linux-image-is-now-azure-linux/ba-p/4236248
> ci(): Azure-cli is no longer based on Alpine so switch apk to apt-get

- config/default/views.view.published_review_dates.yml
Alter published_review_dates View:
- Display published/review dates for anonymous users. 
- Filter by active review_date (otherwise the first inactive date is displayed)
> fix(LP-85): fixes for published_review_dates View

- modules/custom/disclosure_nav/js/disclosure-nav.js
Ensures header and main menu styles are reset when disclosure nav is closed/window is resized
> ECCI-uat-fixes

- modules/custom/ecc_comment/templates/field--ecc-comment.html.twig
When you view a news item with comments enabled,
but before any comments have been added,
the custom styles were missing.
This ensures they are present.
Adds `library_attach` to the relevant template.
https://eccservicetransformation.atlassian.net/browse/LP-128
> Ensure you get custom comment styles even when there's no comments yet.

- config/default/core.entity_view_display.node.localgov_news_article.default.yml
https://eccservicetransformation.atlassian.net/browse/LP-128
we hide the links on the content type because otherwise you get a redundant comment link on nodes with comments
> Hide inline links on news articles
