essexcountycouncil/essex-intranet-drupal

composer.json, composer.lock, config/default/core.extension.yml
Copied `composer.json` and config changes from https://github.com/essexcountycouncil/essex-gov-uk-drupal/pull/113 and ran composer update.
=> Apply drupal version update

modules/custom/ecc_cookie_compliance/ecc_cookie_compliance.libraries.yml
As per https://github.com/essexcountycouncil/essex-gov-uk-drupal/pull/222
=> Fix cookie compliance dependency

config/default/eu_cookie_compliance.settings.yml, patches/localgov_cookie_compliance_save.patch, themes/custom/essex/css/overrides.css, themes/custom/essex/essex.layouts.yml, themes/custom/essex/essex.libraries.yml, themes/custom/essex/layouts/autogrid/ec-autogrid.css, themes/custom/essex/layouts/autogrid/layout--autogrid.html.twig
Change default button text on cookie preference page from 'Save Preferences' to 'Submit Preferences'
=> Ecci 316 cookie button text

README.md, themes/custom/essex/css/overrides.css
now works with logged in and logged out users
=> [bugfix/ECCI-338-mobile-search-position] 

config/default/core.menu.static_menu_link_overrides.yml, config/default/layout_paragraphs.modal_settings.yml, config/default/search_api.index.localgov_directories_index_default.yml, config/default/views.view.localgov_directory_channel.yml
This is the key config file for this commit: `config/default/layout_paragraphs.modal_settings.yml`. The other ones have been overlooked in previous commits and are primarily to do with yaml ordering.
=> ECCI-337: Fixes media w/text image upload issue.

themes/custom/essex/css/overrides.css
=> ECCI-341: Adds grey border to search field and submit button

themes/custom/essex/css/overrides.css, themes/custom/essex/templates/blocks/guides-prev-next-block.html.twig
For some reason this has not made it into develop, so I'm sending it back around by changing the formatting.
=> Task/ecci 255 update styling on previous   next buttons on guide   guide overview

themes/custom/essex/css/overrides.css
Reduce width of the search bar to 764px
Button height - 52px
=> [task/ECCI-363-Search] bugfixes

themes/custom/essex/css/overrides.css
=> [task/ECCI-365-SearchResults] bugfixes

config/default/field.field.node.localgov_subsites_overview.localgov_subsites_content.yml, config/default/field.field.node.localgov_subsites_page.localgov_subsites_content.yml, themes/custom/essex/css/overrides.css
Styles copied from essex-gov-drupal
=> ECCI-397: Contact component in page builder, and styles.

composer.lock, config/default/block.block.essex_localgov_tabs_scarfolk.yml, config/default/core.entity_form_display.node.localgov_guides_overview.default.yml, config/default/core.entity_form_display.node.localgov_services_landing.default.yml, config/default/core.entity_form_display.node.localgov_services_page.default.yml, config/default/core.entity_form_display.node.localgov_services_sublanding.default.yml, config/default/core.entity_form_display.node.localgov_step_by_step_overview.default.yml, config/default/gin.settings.yml
- ECCI-392: Put parent field at top of each node edit form.
- ECCI-389: Enable secondary toolbar, disable tabs block
- Drupal core update 9.5.11
=> ECCI-392 ECC-389 fixes

.gitlab-ci.yml
Adds the SBOM generation and analysis steps to the GitLab pipeline, for monitoring software supply chain.
=> Add SBOM support

assets/composer/services.yml, assets/composer/settings.ddev-custom.php, assets/composer/settings.local.php, assets/composer/settings.php, composer.json, composer.lock, config/default/autologout.role.administrator.yml, config/default/autologout.role.analytics.yml, config/default/autologout.role.emergency_publisher.yml, config/default/autologout.role.localgov_author.yml, config/default/autologout.role.localgov_contributor.yml, config/default/autologout.role.localgov_editor.yml, config/default/autologout.role.localgov_news_editor.yml, config/default/autologout.role.localgov_user_manager.yml, config/default/autologout.settings.yml, config/default/core.extension.yml
- ECCI-422: Use Autologout to force logout after 20 minutes of inactivity. Set gc_maxlifetime to 30 minutes as a fallback.
- Move custom DDEV settings to new file. They shouldn't have been in settings.local.php, and settings.ddev.php is in  .gitignore.
=> ECCI-422: Autologout. Fix DDEV settings.

themes/custom/essex/css/preliminary.css
- card layout more consistent across large mobile, tablet and desktop
=> ECCI-355: amends to card layout

modules/custom/localgov_restricted_content/localgov_restricted_content.module, modules/custom/localgov_restricted_content/templates/localgov-restricted-content-sign-in-with-message.html.twig, modules/custom/localgov_restricted_content/templates/localgov-restricted-content-sign-in.html.twig, themes/custom/essex/templates/content/node--localgov-news-article--full-anonymous.html.twig, themes/custom/essex/templates/restricted-content/localgov-restricted-content-sign-in-with-message.html.twig, themes/custom/essex/templates/restricted-content/localgov-restricted-content-sign-in.html.twig
ECCI-420: After signing in using link on teaser, user should land on the news article.
=> ECCI-420 sign in

themes/custom/essex/css/preliminary.css
- gotcha: same may need to be done for the events cards
- Added styles to break apart rerally long words in the content of the news cards
=> ECCI-481/added-word-wrap-break-word-styles-tonews-cards

config/default/core.entity_form_display.node.localgov_newsroom.default.yml, config/default/core.entity_view_display.node.localgov_newsroom.default.yml, config/default/core.entity_view_display.node.localgov_newsroom.full_anonymous.yml, config/default/field.field.node.localgov_newsroom.localgov_page_components.yml, config/default/field.storage.node.localgov_page_components.yml
Repeat PR due to forced update on release/202311 branch
=> ECCI-464: Optional page component can be added to bottom of newsroom.

themes/custom/essex/js/clickable-teaser.js
- Added some minor changes to the JS
- link is now replaced by the login redirect link for the content if it exists
- otherwise the clickable area takes the user to the desired article
=> ECCI-418/clickable-area-cards-link-updated

.ddev/mutagen/mutagen.yml, .github/PULL_REQUEST_TEMPLATE.md
- Used the documentation outlined on [this page](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
=> ECCI-000: Adds PR template.

config/default/block.block.views_block__published_review_dates_block_publish_review_dates.yml
=> ECCI-502: Remove published/review block from news and subsite overview.

modules/custom/localgov_restricted_content/localgov_restricted_content.module
=> ECCI-515: Temporarily enable hierachical restricted content.

themes/custom/essex/css/curve.css, themes/custom/essex/css/news.css
=> [ECCI-518-MWT-Regressions] regression fixes

themes/custom/essex/css/curve.css
=> Ecci 518 mwt regressions

config/default/block.block.essex_localgov_mainpagecontent_scarfolk.yml, config/default/block.block.essex_localgov_page_header_block_scarfolk.yml, config/default/block.block.essex_localgov_servicescalltoaction_scarfolk.yml, config/default/block.block.eucookiesettingsblock.yml, config/default/block.block.guidecontents.yml, config/default/block.block.partofstepheading.yml, config/default/block.block.strictlynecessarycookies.yml, config/default/menu_item_limit.settings.yml, config/default/system.site.yml
- Feedback form has mailto: link instead of to a page
- Sorts out the `Strictly necessary cookies` block
- Ensures the weights of the block in the content area are in the right order
=> ECCI-514: Config sync from prod to support release.

.ddev/nginx_full/nginx-site.conf, nginx-conf/nginx.conf
Any pages that start with these urls…
- https://intranet.essex.gov.uk/Pages/
- https://intranet.essex.gov.uk/Documents/
… should be redirected to this page
- https://intranet.essex.gov.uk/information-has-moved
Add to Nginx conf for Azure containers and for DDEV.
Same approach as Gov.
=> ECCI-522 LP-24: redirects

.gitlab-ci.yml, README.md, composer.json, composer.lock, config/default/config_ignore.settings.yml, config/default/core.extension.yml, config/default/fathom_analytics.settings.yml, config/default/key.config_override.fathom_id.yml, config/default/key.key.fathom_id.yml
Set Fathom Analytics id from environment variable. Previously it was set through the UI and Config Ignore was intended to protect it. However, the id has disappeared twice in the last few weeks. This new approach ensures that the id cannot be changed.
This is the same approach used on another project.
Need to test this with Gitlab to ensure the environment variable is set
=> ECCI-526: Set Fathom Analytics id from environment variable

.gitlab-ci.yml
Remove an unintended _q_ in .gitlab-ci.yml
=> Update .gitlab-ci.yml - remove typo

composer.json, composer.lock
Shared theme repository added to the composer file so that the themes it can be pulled into this repo
=> [feature/Shared-Theme] added new themes repository to composer

.gitlab-ci.yml
=> Change pipeline so release branches can be deployed straight to preprod.

composer.lock
=> Release/202312 04 update Composer lock

themes/custom/essex/css/news.css, themes/custom/essex/css/preliminary.css
=> [origin/hotfix/ECCI-480] 3col fix

modules/custom/localgov_restricted_content/localgov_restricted_content.module
- It was enabled pre go-live to validate other features
=> ECCI-532: Disable the hierarchical restricted content.

Dockerfile-drupal, composer.lock, config/default/views.view.content_feedback.yml
=> Update ecc_theme. Change imagick download. Change feedback view text.

composer.lock, config/default/block.block.essex_localgov_tabs_scarfolk.yml, config/default/essex.settings.yml, config/default/field.field.media.document.field_media_document.yml, config/default/localgov_restricted_content.settings.yml, modules/custom/localgov_restricted_content/config/install/localgov_restricted_content.settings.yml, modules/custom/localgov_restricted_content/config/schema/localgov_restricted_content.schema.yml, modules/custom/localgov_restricted_content/localgov_restricted_content.info.yml, modules/custom/localgov_restricted_content/localgov_restricted_content.links.menu.yml, modules/custom/localgov_restricted_content/localgov_restricted_content.module, modules/custom/localgov_restricted_content/localgov_restricted_content.permissions.yml, modules/custom/localgov_restricted_content/localgov_restricted_content.routing.yml, modules/custom/localgov_restricted_content/localgov_restricted_content.services.yml, modules/custom/localgov_restricted_content/src/Form/RestrictedContentConfigForm.php, modules/custom/localgov_restricted_content/src/Plugin/Condition/RestrictedContent.php, modules/custom/localgov_restricted_content/src/RestrictedContent.php
=> Merge main into Shared Theme branch

composer.lock
=> ECC Theme 1.0.8

composer.lock
=> Update ecc_theme to 1.0.10

composer.lock
=> Update ecc_theme to 1.0.11

composer.lock
=> Update ecc_theme to 1.0.12

composer.lock
=> Update ecc_theme to 1.0.14

composer.lock
=> Update ecc_theme to 1.0.15

composer.lock
Update to 1.0.16 of shared theme as per [this PR](https://github.com/essexcountycouncil/ecc_theme/pull/28).
=> ECCI-538: Removal of width causes circle to render properly.

composer.lock
This adds the favicons to the Intranet theme.
=> ECCI-550: Shared theme bumped.

composer.lock
=> Update ecc_theme to 1.0.22

.gitlab-ci.yml
ECCI-556: Gitlab changes to match Gov 
- deploy any branch to Develop
- deploy main or release/* to Prod.
=> ECCI-556: Gitlab changes to match Gov

.gitlab-ci.yml, Dockerfile-drupal
- Remove Imagick from Dockerfile
- Allow main and release branches to go straight to Prod.
=> Pipeline fixes

composer.lock
=> Update ecc_theme to 1.0.24

composer.lock
=> Update ecc_theme to 1.0.25

composer.lock
=> Update ecc_theme to 1.0.26

composer.lock
=> Update ecc_theme to 1.0.27

.gitlab-ci.yml
=> ECCI-556: Fix pipeline for deploying develop branch straight to Preprod

composer.lock
=> Update ecc_theme to 1.0.29

composer.lock
=> Update ecc_theme to 1.0.30.

config/default/block.block.ecc_theme_intranet_localgov_tabs_scarfolk.yml
=> LP-87: Enable Tabs block

composer.json, composer.lock
- Apply patch for LGD cookie module for form error. https://github.com/localgovdrupal/localgov_eu_cookie_compliance/issues/23
- Update LGD Forms (forced by dependency on Geocoder)
=> Apply patch for LGD cookie module for form error. Update LGD Forms 

composer.json, composer.lock
Installs the `preview_link` module (https://www.drupal.org/project/preview_link)
Note: I noticed this is already enabled in configuration
=> Install preview_link module ready for review

config/default/core.entity_view_display.node.localgov_step_by_step_page.teaser.yml
=> Hide readmore links from stepbystep page teasers.

config/default/core.date_format.just_human_date.yml, config/default/views.view.published_review_dates.yml
https://eccservicetransformation.atlassian.net/browse/LP-70
changes labels to sentence case, date format to a human date for review, published dates on pages.
Views config change, date format config addition.
=> 202407 datestyle lp 70

.gitlab-ci.yml
=> ci(): Change prod container app name to intranetrb.

.gitlab-ci.yml
=> Release 202407-01: Fix ENVIRONMENT env in .gitlabci deploy-to-prod

composer.lock
https://eccservicetransformation.atlassian.net/browse/LP-214
Update Gin theme to RC13
Resolves broken permissions page
=> Updated Gin theme to RC13 for compatibility with D10.3

.gitlab-ci.yml
New Docker image azure-cli uses tdnf package manager.
=> ci(): Change apt-get to tdnf.

composer.lock, config/default/core.entity_form_display.media.document.default.yml, config/default/core.entity_form_display.media.image.default.yml, config/default/core.entity_form_display.media.remote_video.default.yml, config/default/core.entity_view_display.media.document.default.yml, config/default/core.entity_view_display.media.document.publication.yml, config/default/core.entity_view_display.media.image.default.yml, config/default/core.entity_view_display.media.image.localgov_event_thumbnail.yml, config/default/core.entity_view_display.media.image.localgov_featured.yml, config/default/core.entity_view_display.media.image.localgov_featured_large.yml, config/default/core.entity_view_display.media.image.localgov_newsroom_teaser.yml, config/default/core.entity_view_display.media.image.medium_8_7.yml, config/default/core.entity_view_display.media.image.responsive_3x2.yml, config/default/core.entity_view_display.media.image.responsive_banner.yml, config/default/core.entity_view_display.media.image.scale_crop_7_3_large.yml, config/default/core.entity_view_display.media.image.square.yml, config/default/core.entity_view_display.media.remote_video.default.yml, config/default/field.field.media.document.field_category.yml, config/default/field.field.media.image.field_category.yml, config/default/field.field.media.remote_video.field_category.yml, config/default/field.storage.media.field_category.yml, config/default/taxonomy.vocabulary.media_category.yml, config/default/user.role.localgov_editor.yml, config/default/views.view.media.yml, config/default/views.view.media_library.yml
Creates a new taxonomy (Media category) and fields on media types in order to tag media items and filter on the content media page
=> ECCW-699: Updates to facilitate the management of media files

composer.lock
=> chore(ECCI-578): Drupal core 10.3.8 for security updates

.gitlab-ci.yml, composer.json, composer.lock, config/default/content_lock.settings.yml, config/default/core.entity_form_display.paragraph.localgov_accordion.default.yml, config/default/core.entity_view_display.paragraph.localgov_accordion.default.yml, config/default/core.entity_view_mode.node.localgov_card.yml, config/default/core.extension.yml, config/default/field.field.paragraph.localgov_accordion.localgov_allow_multiple_open.yml, config/default/field.field.paragraph.localgov_accordion.localgov_display_show_hide_all.yml, config/default/field.storage.paragraph.localgov_allow_multiple_open.yml, config/default/field.storage.paragraph.localgov_display_show_hide_all.yml, config/default/layout_paragraphs.modal_settings.yml, config/default/paragraphs.paragraphs_type.from_library.yml, config/default/system.action.node_break_lock_action.yml, config/default/user.role.localgov_author.yml, config/default/user.role.localgov_contributor.yml, config/default/user.role.localgov_editor.yml, config/default/views.view.locked_content.yml, patches/drupal-core-claro.patch
- LP-176: Gin 3.0-RC14
- LP-216: ecc_theme 1.1.14
- Security updates including Drupal 10.3.9
Composer changes since last Prod deployment ([release/2024-release-2](https://github.com/essexcountycouncil/essex-intranet-drupal/tree/release/2024-release-2))
| Production Changes                 | From         | To           | Compare                                                                                      |
|------------------------------------|--------------|--------------|----------------------------------------------------------------------------------------------|
| doctrine/common                    | 3.4.4        | 3.4.5        | [...](https://github.com/doctrine/common/compare/3.4.4...3.4.5)                              |
| doctrine/persistence               | 3.3.3        | …
=> fix(LP-216), fix(LP-176, feat(LP-67), security updates

composer.json, composer.lock, patches/localgov_base_header.patch
=> ECCI-580: Revert update to localgov_base

composer.lock, patches/cludo_search-page-tweaks.patch
UAT bug fixes for main navigation 
- 1.2.29 release for ecc_theme
- Change the patch for Cludo Search to remove PHP warning
=> ECCI-580: Bug fixes from UAT.

modules/custom/disclosure_nav/src/Plugin/Block/ServiceLandingChildPageMenuBlock.php
Fix error when editing a 	Service Landing Child Pages Menu block
=> ECCI-580: Fix node load in block.

composer.lock, modules/custom/disclosure_nav/js/disclosure-nav.js, modules/custom/disclosure_nav/templates/service-landing-page-child-pages-nav.html.twig
Fixes mobile nav height issues and nav closing on scroll issue while also ensuring open menu closes when the other menu is toggled.
=> ECCI-uat-fixes

config/default/user.role.localgov_editor.yml
Allow editors to edit and delete polls. Permission change
https://eccservicetransformation.atlassian.net/browse/LP-277
=> Allow editors to edit and delete polls

config/default/user.role.localgov_news_editor.yml
https://eccservicetransformation.atlassian.net/browse/LP-277
=> Allow news editors to see the poll overview page

modules/custom/disclosure_nav/js/disclosure-nav.js
=> ECCI-more-uat-fixes: Resolves issue of menu obscuring content on mobile devices

modules/custom/disclosure_nav/disclosure_nav.libraries.yml
Add version to the disclosure library,
=> ECCI-580: Add JS library version to bust caching.

modules/custom/disclosure_nav/disclosure_nav.libraries.yml, modules/custom/disclosure_nav/js/disclosure-nav.js
=> ECCI-more-uat-fixes: Adds a scroll check to prevent header height resetting on scroll

modules/custom/disclosure_nav/disclosure_nav.libraries.yml, modules/custom/disclosure_nav/js/disclosure-nav.js
=> Bugfix/ecci more uat fixes: Removes header height reset from onBlur method and moves to window resize
